server:
  port: 9090

spring:
  #postgres
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    url: ENC(wuq/JNEohnF+fO3cbBiEvAzV1vDBthdTywA1Em/NZQnSd4Ia4P+Si6qi7uel+oMyGtzORun6UfYtAxXnMez7NA==)
    username: ENC(FXOIlq05aKyie1Eaei6MYiM/30DGWlU1)
    password: ENC(lkIo4yXZo/W7voUPLr5NRpCxL6zCtPHHZ0+iP7a9jkQ=)
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      url: ENC(KcJ5FQHY4MxVzUNJ6pqxFT7JOUsoi/NlatlZCHbCM/0=)
      host: ENC(vewwyQ0zMOe77WvwzphNSqF0vAjbkvGP+mkABZCw8to=)
      port: ${MONGODB_PORT}
      database: ENC(QYRSKr0uZOD+6mFChXcyMg==)
    redis:
      host: ENC(lqIzI0VbWenMVmGDjODMtfaIxoiK08DbDKPHc8bXRlA=)
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

tmap:
  road-expiration-time: 86400000  # 24시간
  api:
    key: ENC(LWYqblI6wJLRaVTlZfDM9szPGHE2EZ21lIVhOYiFy3QBvYSTOm+l/Y3iyM9T8Bs/Gmo09b1NCvM=)


jwt:
  token:
    secret: ENC(lmJzRIHGpaOr4n/F3pQZOtS38/chsswL9txKR96MNZKswdJnwp2KEit0oD7tkWiCwwxeH4XiNErkNZ6i3V4a81YVq7PgyWuArF+5V9HDoxTrCTmmhsyxk7lCcMOX8MGu31h6Jhwi67v3ri6/N4fJBgOvhqolRbtvrRO00u7ooOE=)
    access-expiration-time: 3600000 #1시간
    refresh-expiration-time: 86400000 #24시간

cloud:
  aws:
    s3:
      bucket: ENC(D3WremaoJraLKEONkOC/jg==)
      base-url: ENC(Uy/GzWij/acXMHP0+qXHxVBzv4UaNmzgWy/cm11ugTI5knpds9gNlgCeXUZ9WPNnxXJg+r8hp+s=)
    credentials:
      access-key: ENC(EZIkbuGlEWiYVEcqEWH7nis9QKLo7rhnsoRy16DwU1s=)
      secret-key: ENC(TxoY84Jj/3l2kvMtq67vW1Ee2l6HlSR7N81MNWKZLJaBIoI4LMssLe9o3QBICPOe6uSF34UhXY0=)
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

